routes/web.php
<?php

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\PurchaseReturnController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellReturnController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\SupplierController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[SiteController::class,'index'])->name('login');
Route::post('/login',[SiteController::class,'login'])->name('storeLogin');



Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function(){
    Route::get('/',[DashboardController::class,'index'])->name('dashboard');

    Route::get('/logout',[SiteController::class,'logout'])->name('logout');

    //Product Routes
    Route::prefix('product')->name('products.')->group(function(){
        Route::get('/',[ProductController::class,'index'])->name('index');
        Route::get('/create',[ProductController::class,'create'])->name('create');
        Route::post('/store',[ProductController::class,'store'])->name('store');
        Route::get('/delete/{id}',[ProductController::class,'destroy'])->name('destroy');
        Route::get('/edit/{id}',[ProductController::class,'edit'])->name('edit');
        Route::post('/update/{id}',[ProductController::class,'update'])->name('update');
        Route::get('/getDataById',[ProductController::class,'getDataById'])->name('getDataById');
    });


    //Customer Routes
    Route::prefix('customer')->name('customer.')->group(function(){
        Route::get('/',[CustomerController::class,'index'])->name('index');
        Route::get('/create',[CustomerController::class,'create'])->name('create');
        Route::post('/store',[CustomerController::class,'store'])->name('store');
        Route::get('/delete/{id}',[CustomerController::class,'destroy'])->name('destroy');
        Route::get('/edit/{id}',[CustomerController::class,'edit'])->name('edit');
        Route::post('/update/{id}',[CustomerController::class,'update'])->name('update');
    });

    //Supplier Routes
    Route::prefix('supplier')->name('supplier.')->group(function(){
        Route::get('/',[SupplierController::class,'index'])->name('index');
        Route::get('/create',[SupplierController::class,'create'])->name('create');
        Route::post('/store',[SupplierController::class,'store'])->name('store');
        Route::get('/delete/{id}',[SupplierController::class,'destroy'])->name('destroy');
        Route::get('/edit/{id}',[SupplierController::class,'edit'])->name('edit');
        Route::post('/update/{id}',[SupplierController::class,'update'])->name('update');
    });

    //Sell Routes
    Route::prefix('sell')->name('sell.')->group(function(){
        Route::get('/',[SellController::class,'index'])->name('index');
        Route::get('/create',[SellController::class,'create'])->name('create');
        Route::post('/store',[SellController::class,'store'])->name('store');
        Route::get('/delete/{id}',[SellController::class,'destroy'])->name('destroy');
        Route::get('/detail/{id}',[SellController::class,'show'])->name('show');
    });

    //Purchase Routes
    Route::prefix('purchase')->name('purchase.')->group(function(){
        Route::get('/',[PurchaseController::class,'index'])->name('index');
        Route::get('/create',[PurchaseController::class,'create'])->name('create');
        Route::post('/store',[PurchaseController::class,'store'])->name('store');
        Route::get('/delete/{id}',[PurchaseController::class,'destroy'])->name('destroy');
        Route::get('/detail/{id}',[PurchaseController::class,'show'])->name('show');
    });

    //Sell Return Routes
    Route::prefix('sell_return')->name('sell_return.')->group(function(){
        Route::get('/',[SellReturnController::class,'index'])->name('index');
        Route::get('/create',[SellReturnController::class,'create'])->name('create');
        Route::post('/store',[SellReturnController::class,'store'])->name('store');
        Route::get('/delete/{id}',[SellReturnController::class,'destroy'])->name('destroy');
        Route::get('/detail/{id}',[SellReturnController::class,'show'])->name('show');
    });

    //Purchase Return Routes
    Route::prefix('purchase_return')->name('purchase_return.')->group(function(){
        Route::get('/',[PurchaseReturnController::class,'index'])->name('index');
        Route::get('/create',[PurchaseReturnController::class,'create'])->name('create');
        Route::post('/store',[PurchaseReturnController::class,'store'])->name('store');
        Route::get('/delete/{id}',[PurchaseReturnController::class,'destroy'])->name('destroy');
        Route::get('/detail/{id}',[PurchaseReturnController::class,'show'])->name('show');
    });
    //Report Routes
    Route::prefix('report')->name('report.')->group(function(){
        Route::get('/',[ReportController::class,'report'])->name('report');
    });

});

app/Http/Controllers/PurchaseReturnController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use App\Models\Product;
use App\Models\Transaction;
use App\Models\TransactionDetails;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use DB;


class PurchaseReturnController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            \Session::put('menu','purchase_return');
            return $next($request);
        });
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $purchases = Transaction::where('type',Transaction::PURCHASE_RETURN)->get();
        return view('admin.purchaseReturn.index',compact('purchases'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Contact::where('type',Contact::SUPPLIER)->get();
        $products = Product::all();
        return view('admin.purchaseReturn.create',compact('customers','products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->except(['token','product']);
        DB::beginTransaction();
        try {

            //Save Transaction Data
            $transaction = new Transaction();
            //Invoice Number Save Dummy
            $transaction->invoice_number = '-';
            $transaction->type = Transaction::PURCHASE_RETURN;
            $transaction->customer_id = $data['customer'];
            $transaction->tax = isset($data['tax'])?$data['tax']:0;
            $transaction->discount = isset($data['discount'])?$data['discount']:0;
            $transaction->save();


            $total = 0;

            //Save Transaction Detail Data
            foreach ($data['id'] as $key => $value) {
                $transactionDetail = new TransactionDetails();
                $transactionDetail->transaction_id = $transaction->id;
                $transactionDetail->product_id = $value;
                $transactionDetail->qty = $data['qty'][$key];

                $product = Product::getPricingFromId($value);
                if(!isset($product)){
                    DB::rollback();
                    return redirect()->back()->withErrors('ID Product Not Found !');
                }

                $qty = Product::minusQtyProductFromId($value,$data['qty'][$key]);
                if($qty['success'] == 0){
                    DB::rollback();
                    return redirect()->back()->withErrors($qty['msg']);
                }


                $transactionDetail->purchase_price = $product['purchase_price'];
                $transactionDetail->sell_price = $product['sell_price'];
                $transactionDetail->save();

                $total += $transactionDetail->qty * $transactionDetail->purchase_price;
            }

            $transaction->total = $total;
            $totalWithoutTax = $total - $transaction->discount;
            //Invoice Number for Generated
            $transaction->invoice_number = isset($data['invoice_number'])?$data['invoice_number']:Transaction::generateInvoiceNumber($transaction->id);
            $transaction->grand_final = $totalWithoutTax - (($transaction->tax > 0)?$totalWithoutTax*$transaction->tax/100:0);
            $transaction->save();


            DB::commit();
            return redirect()->route('admin.purchase_return.index')->with('success','Berhasil Menambahkan Data!');
        } catch (\Exception $e) {
            DB::rollback();
            Log::emergency($e->getFile() . ' - ' . $e->getLine() . ' - '. $e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaction = Transaction::find($id);
        return view('admin.purchaseReturn.details',compact('transaction'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try {

            $detail = DB::table('transactions_details')->where('id',$id)->delete();
            $transaction = Transaction::where('id',$id)->delete();

            DB::commit();
            return redirect()->route('admin.purchase_return.index')->with('success','Berhasil Menghapus Data!');
        } catch (\Exception $e) {
            DB::rollback();
            Log::emergency($e->getFile() . ' - ' . $e->getLine() . ' - '. $e->getMessage());
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

resources/views/admin/purchaseReturn/create.blade.php
@extends('partials.main')
@section('content')
@include('partials.sidebar')
<div class="content-page">
     <div class="container-fluid add-form-list">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="header-title">
                            <h4 class="card-title">Add Purchase Return</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('admin.purchase_return.store')}}" method="POST" enctype="multipart/form-data" data-toggle="validator">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Invoice Number *</label>
                                        <input type="text" class="form-control" name="invoice_number" placeholder="Enter Invoice Number (Blank for auto Generate)">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Supplier *</label>
                                        <select name="customer" class="form-control select2">
                                            @foreach ($customers as $customer)
                                                <option value="{{$customer->id}}">{{$customer->name}}</option>
                                            @endforeach
                                        </select>
                                         <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Product</label>
                                        <select name="product" id="product" class="form-control select2">
                                            <option value="" readonly>Select Product</option>
                                            @foreach ($products as $product)
                                                <option value="{{$product->id}}">{{$product->name}}</option>
                                            @endforeach
                                        </select>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="table-responsive rounded mb-3">
                                    <table class="data-tables-no-search table mb-0 tbl-server-info">
                                        <thead class="bg-white text-uppercase">
                                            <tr class="ligth ligth-data">
                                                <th>Product</th>
                                                <th>Price</th>
                                                <th>Qty</th>
                                                <th>Subtotal</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody class="ligth-body" id="product_data">

                                        </tbody>
                                    </table>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Tax</label>
                                        <input type="number" class="form-control" name="tax" placeholder="Enter Tax in Percent (%)" data-errors="Enter Tax in Percent(%)">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Discount </label>
                                        <input type="number" class="form-control" name="discount" placeholder="Enter Discount (Fixed Rate)" data-errors="Enter Discount (Fixed Rate).">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Add Purchase</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page end  -->
@endsection
@section('script')
    <script>
        function numberWithCommas(x) {
            return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
        }
        $(document).ready(function() {
            $('.select2').select2({
                theme: "bootstrap4"
            });
        });
        $('.select2').on('select2:select', function (e) {
            var data = e.params.data.id;
            if(data != ""){
                $.ajax({
                    url :"{{route('admin.products.getDataById')}}",
                    data : {id:data},
                    cache:false,
                    success:function(data){
                        var stringAppend = "";
                        stringAppend += "<tr>";
                        stringAppend += "<input type='hidden' name='id[]' value='"+data.id+"'>";
                        stringAppend += "<td>"+data.name+"</td>";
                        stringAppend += "<td data-price='"+data.purchase_price+"' class='purchase_price'>Rp. "+numberWithCommas(data.purchase_price)+"</td>";
                        stringAppend += "<td class='col-md-2'><input type='text' class='form-control changeSubtotal' value='1' min='1' name='qty[]'></td>";
                        stringAppend += "<td class='subtotal'>Rp. "+numberWithCommas(data.purchase_price)+"</td>";
                        stringAppend += '<td><div class="d-flex align-items-center list-action"> <a class="badge bg-warning mr-2 deleteLine" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"><i class="ri-delete-bin-line mr-0"></i></a></div></td>';
                        stringAppend += "</tr>";
                        $("#product_data").append(stringAppend);
                    }
                });
            }
        });

        $(document).on("click",".deleteLine",function(){
            $(this).parent().parent().parent().remove();
        });
        $(document).on("keyup",".changeSubtotal",function () {
            if (this.value != this.value.replace(/[^0-9\.]/g, '')) {
                this.value = this.value.replace(/[^0-9\.]/g, '');
            }
            var price = $(this).parent().parent().find('.purchase_price').data("price");
            var qty = $(this).val();
            var total = qty * price;
            $(this).parent().parent().find(".subtotal").text("Rp. "+numberWithCommas(total));
        });
    </script>
@endsection

resources/views/admin/purchaseReturn/details.blade.php
@extends('partials.main')
@section('content')
@include('partials.sidebar')
<div class="content-page">
      <div class="container-fluid">
         <div class="row">
            <div class="col-lg-12">
               <div class="card card-block card-stretch card-height print rounded">
                  <div class="card-header d-flex justify-content-between bg-primary header-invoice">
                        <div class="iq-header-title">
                           <h4 class="card-title mb-0">{{$transaction->invoice_number}}</h4>
                        </div>
                  </div>
                  <div class="card-body">
                        <div class="row">
                           <div class="col-lg-12">
                              <div class="table-responsive-sm">
                                    <table class="table">
                                       <thead>
                                          <tr>
                                                <th scope="col">Order Date</th>
                                                <th scope="col">Supplier Name</th>
                                                <th scope="col">Supplier Email</th>
                                                <th scope="col">Phone Number</th>
                                                <th scope="col">Address</th>
                                          </tr>
                                       </thead>
                                       <tbody>
                                          <tr>
                                                <td>{{date('d M Y H:i',strtotime($transaction->created_at))}}</td>
                                                <td>{{$transaction->customer->name}}</td>
                                                <td>{{$transaction->customer->email}}</td>
                                                <td>{{$transaction->customer->phone}}</td>
                                                <td>{{$transaction->customer->address}}</td>
                                          </tr>
                                       </tbody>
                                    </table>
                              </div>
                           </div>
                        </div>
                        <div class="row">
                           <div class="col-sm-12">
                              <h5 class="mb-3">Purchase Summary</h5>
                              <div class="table-responsive-sm">
                                    <table class="table">
                                       <thead>
                                          <tr>
                                                <th class="text-center" scope="col">#</th>
                                                <th scope="col">Item</th>
                                                <th class="text-center" scope="col">Quantity</th>
                                                <th class="text-center" scope="col">Price</th>
                                                <th class="text-center" scope="col">Totals</th>
                                          </tr>
                                       </thead>
                                       <tbody>
                                           @foreach ($transaction->transactionDetails as $key => $value)
                                                <tr>
                                                        <th class="text-center" scope="row">{{$key+1}}</th>
                                                        <td>
                                                            <h6 class="mb-0">{{$value->product->name}}</h6>
                                                        </td>
                                                        <td class="text-center">{{$value->qty}}</td>
                                                        <td class="text-center">Rp. {{number_format($value->sell_price,2,',','.')}}</td>
                                                        <td class="text-center"><b>Rp. {{number_format($value->sell_price * $value->qty,2,',','.')}}</b></td>
                                                </tr>
                                           @endforeach
                                       </tbody>
                                    </table>
                              </div>
                           </div>
                        </div>
                        <div class="row mt-4 mb-3">
                           <div class="offset-lg-8 col-lg-4">
                              <div class="or-detail rounded">
                                    <div class="p-3">
                                       <h5 class="mb-3">Purchase Details</h5>
                                       <div class="mb-2">
                                          <h6>Sub Total</h6>
                                          <p>Rp. {{number_format($transaction->total,2,',','.')}}</p>
                                       </div>
                                       <div class="mb-2">
                                          <h6>Discount</h6>
                                          <p>Rp. {{number_format($transaction->discount,2,',','.')}}</p>
                                       </div>
                                       <div class="mb-2">
                                          <h6>Tax (%)</h6>
                                          <p>{{number_format($transaction->tax,1,',','.')}} %</p>
                                       </div>
                                    </div>
                                    <div class="ttl-amt py-2 px-3 d-flex justify-content-between align-items-center">
                                       <h6>Total</h6>
                                       <h3 class="text-primary font-weight-700">Rp. {{number_format($transaction->grand_final,2,',','.')}}</h3>
                                    </div>
                              </div>
                           </div>
                        </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
    </div>
@endsection

resources/views/admin/purchaseReturn/index.blade.php
@extends('partials.main')
@section('content')
@include('partials.sidebar')
<div class="content-page">
    <div class="container-fluid">
       <div class="row">
           <div class="col-lg-12">
               <div class="d-flex flex-wrap flex-wrap align-items-center justify-content-between mb-4">
                   <div>
                       <h4 class="mb-3">List Purchase Return</h4>
                   </div>
                   <a href="{{route('admin.purchase_return.create')}}" class="btn btn-primary add-list"><i class="las la-plus mr-3"></i>Add Purchase Return</a>
               </div>
           </div>
           <div class="col-lg-12">
               <div class="table-responsive rounded mb-3">
               <table class="data-tables table mb-0 tbl-server-info">
                   <thead class="bg-white text-uppercase">
                       <tr class="ligth ligth-data">
                        <th>Transaction Date</th>
                           <th>Invoice Number</th>
                           <th>Total Purchase Return</th>
                           <th>Discount</th>
                           <th>Tax</th>
                           <th>Final Total</th>
                           <th>Action</th>
                       </tr>
                   </thead>
                   <tbody class="ligth-body">
                       @foreach ($purchases as $purchase)
                            <tr>
                                <td>{{date('d M Y H:i',strtotime($purchase->created_at))}}</td>
                                <td>{{$purchase->invoice_number}}</td>
                                <td>Rp. {{number_format($purchase->total,2,',','.')}}</td>
                                <td>Rp. {{number_format($purchase->discount,2,',','.')}}</td>
                                <td>{{number_format($purchase->tax,1,',','.')}} %</td>
                                <td>Rp. {{number_format($purchase->grand_final,2,',','.')}}</td>
                                <td>
                                    <div class="d-flex align-items-center list-action">
                                        <a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Details"
                                            href="{{route('admin.purchase.show',$purchase->id)}}">
                                            <svg class="svg-icon" id="p-dash7" width="20" height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline>
                                            </svg>
                                        </a>
                                        <a class="badge bg-warning mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"
                                            href="{{route('admin.purchase.destroy',$purchase->id)}}" onclick="return confirm('Are you Sure?')"><i class="ri-delete-bin-line mr-0"></i></a>
                                    </div>
                                </td>
                            </tr>
                       @endforeach
                   </tbody>
               </table>
               </div>
           </div>
       </div>
       <!-- Page end  -->
   </div>
@endsection