routes/web.php
<?php

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\PurchaseReturnController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellReturnController;
use App\Http\Controllers\SiteController;
use App\Http\Controllers\SupplierController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[SiteController::class,'index'])->name('login');
Route::post('/login',[SiteController::class,'login'])->name('storeLogin');



Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function(){
    Route::get('/',[DashboardController::class,'index'])->name('dashboard');

    Route::get('/logout',[SiteController::class,'logout'])->name('logout');

    //Product Routes
    Route::prefix('product')->name('products.')->group(function(){
        Route::get('/',[ProductController::class,'index'])->name('index');
        Route::get('/create',[ProductController::class,'create'])->name('create');
        Route::post('/store',[ProductController::class,'store'])->name('store');
        Route::get('/delete/{id}',[ProductController::class,'destroy'])->name('destroy');
        Route::get('/edit/{id}',[ProductController::class,'edit'])->name('edit');
        Route::post('/update/{id}',[ProductController::class,'update'])->name('update');
        Route::get('/getDataById',[ProductController::class,'getDataById'])->name('getDataById');
    });


    //Customer Routes
    Route::prefix('customer')->name('customer.')->group(function(){
        Route::get('/',[CustomerController::class,'index'])->name('index');
        Route::get('/create',[CustomerController::class,'create'])->name('create');
        Route::post('/store',[CustomerController::class,'store'])->name('store');
        Route::get('/delete/{id}',[CustomerController::class,'destroy'])->name('destroy');
        Route::get('/edit/{id}',[CustomerController::class,'edit'])->name('edit');
        Route::post('/update/{id}',[CustomerController::class,'update'])->name('update');
    });

    //Supplier Routes
    Route::prefix('supplier')->name('supplier.')->group(function(){
        Route::get('/',[SupplierController::class,'index'])->name('index');
        Route::get('/create',[SupplierController::class,'create'])->name('create');
        Route::post('/store',[SupplierController::class,'store'])->name('store');
        Route::get('/delete/{id}',[SupplierController::class,'destroy'])->name('destroy');
        Route::get('/edit/{id}',[SupplierController::class,'edit'])->name('edit');
        Route::post('/update/{id}',[SupplierController::class,'update'])->name('update');
    });

    //Sell Routes
    Route::prefix('sell')->name('sell.')->group(function(){
        Route::get('/',[SellController::class,'index'])->name('index');
        Route::get('/create',[SellController::class,'create'])->name('create');
        Route::post('/store',[SellController::class,'store'])->name('store');
        Route::get('/delete/{id}',[SellController::class,'destroy'])->name('destroy');
        Route::get('/detail/{id}',[SellController::class,'show'])->name('show');
    });

    //Purchase Routes
    Route::prefix('purchase')->name('purchase.')->group(function(){
        Route::get('/',[PurchaseController::class,'index'])->name('index');
        Route::get('/create',[PurchaseController::class,'create'])->name('create');
        Route::post('/store',[PurchaseController::class,'store'])->name('store');
        Route::get('/delete/{id}',[PurchaseController::class,'destroy'])->name('destroy');
        Route::get('/detail/{id}',[PurchaseController::class,'show'])->name('show');
    });

    //Sell Return Routes
    Route::prefix('sell_return')->name('sell_return.')->group(function(){
        Route::get('/',[SellReturnController::class,'index'])->name('index');
        Route::get('/create',[SellReturnController::class,'create'])->name('create');
        Route::post('/store',[SellReturnController::class,'store'])->name('store');
        Route::get('/delete/{id}',[SellReturnController::class,'destroy'])->name('destroy');
        Route::get('/detail/{id}',[SellReturnController::class,'show'])->name('show');
    });

    //Purchase Return Routes
    Route::prefix('purchase_return')->name('purchase_return.')->group(function(){
        Route::get('/',[PurchaseReturnController::class,'index'])->name('index');
        Route::get('/create',[PurchaseReturnController::class,'create'])->name('create');
        Route::post('/store',[PurchaseReturnController::class,'store'])->name('store');
        Route::get('/delete/{id}',[PurchaseReturnController::class,'destroy'])->name('destroy');
        Route::get('/detail/{id}',[PurchaseReturnController::class,'show'])->name('show');
    });
    //Report Routes
    Route::prefix('report')->name('report.')->group(function(){
        Route::get('/',[ReportController::class,'report'])->name('report');
    });

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $table = 'products';

    public function product()
    {
        return $this->belongsTo(TransactionDetails::class,'id','product_id');
    }

    public function getPricingFromId($id)
    {
        $data = Product::where('id',$id)
                ->select('sell_price','purchase_price')
                ->first()->toArray();

        return $data;
    }

    public function minusQtyProductFromId($id,$minus)
    {
        $data = Product::find($id);

        if(!isset($data)){
            $output = [
                'success' => 0,
                'msg' => 'product ID tidak Ditemukan'
            ];
            return $output;
        }

        if($data->qty - $minus < 0 ){
            $output = [
                'success' => 0,
                'msg' => 'Qty tidak cukup untuk product ['.$data->name.']'
            ];
            return $output;
        }

        $data->qty = $data->qty - $minus;
        $data->save();


        $output = [
            'success' => 1,
            'msg' => 'Berhasil Menambahkan Data!'
        ];
        return $output;
    }

    public function plusQtyProductFromId($id,$plus)
    {
        $data = Product::find($id);

        if(!isset($data)){
            $output = [
                'success' => 0,
                'msg' => 'product ID tidak Ditemukan'
            ];
            return $output;
        }

        $data->qty = $data->qty + $plus;
        $data->save();


        $output = [
            'success' => 1,
            'msg' => 'Berhasil Menambahkan Data!'
        ];
        return $output;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ProductController extends Controller
{

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            \Session::put('menu','product');
            return $next($request);
        });
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name'=>'required',
            'code'=>'required|unique:products,code',
            'qty'=>'required|numeric|min:0',
            'purchase_price'=>'required|numeric|min:0',
            'selling_price'=>'required|numeric|min:0',
        ];

        $data = $request->all();

        $validate = Validator::make($data,$rules);
        if($validate->fails()){
            return redirect()->back()->withErrors('Validation Errors');
        }

        $product = new Product();
        $product->name = $data['name'];
        $product->code = $data['code'];
        $product->qty = $data['qty'];
        $product->sell_price = $data['selling_price'];
        $product->purchase_price = $data['purchase_price'];
        $product->description = $data['description'];
        if($request->file('image')){
            $file = $request->file('image');
            $filename= date('YmdHis').$file->getClientOriginalName();
            $file->move(public_path('image'), $filename);
            $product->image = "/image/".$filename;
        }
        $product->save();

        return redirect()->route('admin.products.index')->with('success','Berhasil Menambahkan Data!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        return view('admin.product.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name'=>'required',
            'code'=>'required|unique:products,code,'.$id,
            'purchase_price'=>'required|numeric|min:0',
            'selling_price'=>'required|numeric|min:0',
        ];

        $data = $request->all();

        $validate = Validator::make($data,$rules);
        if($validate->fails()){
            return redirect()->back()->withErrors('Validation Errors');
            dd($validate->errors());
        }

        $product = Product::find($id);
        $product->name = $data['name'];
        $product->code = $data['code'];
        // $product->qty = $data['qty'];
        $product->sell_price = $data['selling_price'];
        $product->purchase_price = $data['purchase_price'];
        $product->description = $data['description'];
        if($request->file('image')){
            $file = $request->file('image');
            $filename= date('YmdHis').$file->getClientOriginalName();
            $file->move(public_path('image'), $filename);
            $product->image = "/image/".$filename;
        }
        $product->update();

        return redirect()->route('admin.products.index')->with('success','Berhasil Mengubah Data!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        if(!isset($product)){
            return redirect()->back()->withErrors('ID Not Found');
        }
        $product->delete();
        return redirect()->back()->with('success','Berhasil Menghapus Data!');
    }

    public function getDataById(Request $request)
    {

        if(!isset($request->id)){
            return false;
        }
        $product = Product::find($request->id);


        return $product;
    }
}

resources/views/admin/product/create.blade.php
@extends('partials.main')
@section('content')
@include('partials.sidebar')
<div class="content-page">
     <div class="container-fluid add-form-list">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="header-title">
                            <h4 class="card-title">Add Product</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('admin.products.store')}}" method="POST" enctype="multipart/form-data" data-toggle="validator">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Name *</label>
                                        <input type="text" class="form-control" name="name" placeholder="Enter Name" data-errors="Please Enter Name." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Code *</label>
                                        <input type="text" class="form-control" name="code" placeholder="Enter Code" data-errors="Please Enter Code." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Purchase Price *</label>
                                        <input type="number" class="form-control" name="purchase_price" placeholder="Enter Cost" data-errors="Enter Purchase Price." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Selling Price *</label>
                                        <input type="number" class="form-control" name="selling_price" placeholder="Enter Price" data-errors="Enter Selling Price." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Quantity *</label>
                                        <input type="number" class="form-control" name="qty" placeholder="Enter Quantity" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Image</label>
                                        <input type="file" class="form-control image-file" name="image" accept="image/*">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Description / Product Details</label>
                                        <textarea class="form-control" rows="4" name="description"></textarea>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Add Product</button>
                            <button type="reset" class="btn btn-danger">Reset</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page end  -->
@endsection

resources/views/admin/product/edit.blade.php
@extends('partials.main')
@section('content')
@include('partials.sidebar')
<div class="content-page">
     <div class="container-fluid add-form-list">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div class="header-title">
                            <h4 class="card-title">Edit Product</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('admin.products.update',$product->id)}}" method="POST" enctype="multipart/form-data" data-toggle="validator">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Name *</label>
                                        <input type="text" class="form-control" name="name" value="{{$product->name}}" placeholder="Enter Name" data-errors="Please Enter Name." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Code *</label>
                                        <input type="text" class="form-control" name="code"  value="{{$product->code}}" placeholder="Enter Code" data-errors="Please Enter Code." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Purchase Price *</label>
                                        <input type="number" class="form-control" name="purchase_price"  value="{{$product->purchase_price}}" placeholder="Enter Cost" data-errors="Enter Purchase Price." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Selling Price *</label>
                                        <input type="number" class="form-control" name="selling_price"  value="{{$product->sell_price}}" placeholder="Enter Price" data-errors="Enter Selling Price." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Quantity *</label>
                                        <input type="number" class="form-control" name="qty" value="{{$product->qty}}" placeholder="Enter Quantity" disabled>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Image</label>
                                        <input type="file" class="form-control image-file" name="image" accept="image/*">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Description / Product Details</label>
                                        <textarea class="form-control" rows="4" name="description">{{$product->description}}</textarea>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Update Product</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page end  -->
@endsection

resources/views/admin/product/index.blade.php
@extends('partials.main')
@section('content')
@include('partials.sidebar')
<div class="content-page">
    <div class="container-fluid">
       <div class="row">
           <div class="col-lg-12">
               <div class="d-flex flex-wrap flex-wrap align-items-center justify-content-between mb-4">
                   <div>
                       <h4 class="mb-3">Product List</h4>
                   </div>
                   <a href="{{route('admin.products.create')}}" class="btn btn-primary add-list"><i class="las la-plus mr-3"></i>Add Product</a>
               </div>
           </div>
           <div class="col-lg-12">
               <div class="table-responsive rounded mb-3">
               <table class="data-tables table mb-0 tbl-server-info">
                   <thead class="bg-white text-uppercase">
                       <tr class="ligth ligth-data">
                           <th>Product</th>
                           <th>Code</th>
                           <th>Category</th>
                           <th>Quantity</th>
                           <th>Price</th>
                           <th>Cost</th>
                           <th>Action</th>
                       </tr>
                   </thead>
                   <tbody class="ligth-body">
                       @foreach ($products as $product)
                            <tr>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <img src="{{$product->image}}" class="img-fluid rounded avatar-50 mr-3" alt="image">
                                        <div>
                                            {{$product->name}}
                                        </div>
                                    </div>
                                </td>
                                <td>{{$product->code}}</td>
                                <td>Beauty</td>
                                <td>{{number_format($product->qty,2,',','.')}}</td>
                                <td>Rp. {{number_format($product->sell_price,2,',','.')}}</td>
                                <td>Rp. {{number_format($product->purchase_price,2,',','.')}}</td>
                                <td>
                                    <div class="d-flex align-items-center list-action">
                                        <a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"
                                            href="{{route('admin.products.edit',$product->id)}}"><i class="ri-pencil-line mr-0"></i></a>
                                        <a class="badge bg-warning mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete"
                                            href="{{route('admin.products.destroy',$product->id)}}" onclick="return confirm('Are you Sure?')"><i class="ri-delete-bin-line mr-0"></i></a>
                                    </div>
                                </td>
                            </tr>
                       @endforeach
                   </tbody>
               </table>
               </div>
           </div>
       </div>
       <!-- Page end  -->
   </div>
@endsection